// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEgxoBpw7NzjI9P2-bKF5EGi3jK05sFzM',
    appId: '1:98695526673:web:1488049be30d4263b174b0',
    messagingSenderId: '98695526673',
    projectId: 'templeapp-cf43e',
    authDomain: 'templeapp-cf43e.firebaseapp.com',
    storageBucket: 'templeapp-cf43e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA37Yn0AGnZYb-P2MDiG1WaW8PcTxmCZVg',
    appId: '1:98695526673:android:8ed49b0db59ee290b174b0',
    messagingSenderId: '98695526673',
    projectId: 'templeapp-cf43e',
    storageBucket: 'templeapp-cf43e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZh_yLmxr5siNu8zyJLOI3iGc0-1eJtj0',
    appId: '1:98695526673:ios:1819215ef5589256b174b0',
    messagingSenderId: '98695526673',
    projectId: 'templeapp-cf43e',
    storageBucket: 'templeapp-cf43e.firebasestorage.app',
    iosBundleId: 'com.gracebiblechurch.templeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZh_yLmxr5siNu8zyJLOI3iGc0-1eJtj0',
    appId: '1:98695526673:ios:1819215ef5589256b174b0',
    messagingSenderId: '98695526673',
    projectId: 'templeapp-cf43e',
    storageBucket: 'templeapp-cf43e.firebasestorage.app',
    iosBundleId: 'com.gracebiblechurch.templeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEgxoBpw7NzjI9P2-bKF5EGi3jK05sFzM',
    appId: '1:98695526673:web:00f92097b9692873b174b0',
    messagingSenderId: '98695526673',
    projectId: 'templeapp-cf43e',
    authDomain: 'templeapp-cf43e.firebaseapp.com',
    storageBucket: 'templeapp-cf43e.firebasestorage.app',
  );
}
